/*
 * generated by Xtext 2.30.0
 */
package com.mdsd.assignment2.ui;

import com.google.inject.Injector;
import com.mdsd.assignment2.ui.internal.Assignment2Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathdslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Assignment2Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Assignment2Activator activator = Assignment2Activator.getInstance();
		return activator != null ? activator.getInjector(Assignment2Activator.COM_MDSD_ASSIGNMENT2_MATHDSL) : null;
	}

}
