/*
 * generated by Xtext 2.30.0
 */
package com.mdsd.assignment2;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MathdslStandaloneSetup extends MathdslStandaloneSetupGenerated {

	public static void doSetup() {
		new MathdslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
