/**
 * generated by Xtext 2.30.0
 */
package ui.languagedsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ui.languagedsl.Component#getLayout <em>Layout</em>}</li>
 *   <li>{@link ui.languagedsl.Component#getElement <em>Element</em>}</li>
 *   <li>{@link ui.languagedsl.Component#getFormuse <em>Formuse</em>}</li>
 * </ul>
 *
 * @see ui.languagedsl.LanguagedslPackage#getComponent()
 * @model
 * @generated
 */
public interface Component extends EObject
{
  /**
   * Returns the value of the '<em><b>Layout</b></em>' containment reference list.
   * The list contents are of type {@link ui.languagedsl.Layout}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layout</em>' containment reference list.
   * @see ui.languagedsl.LanguagedslPackage#getComponent_Layout()
   * @model containment="true"
   * @generated
   */
  EList<Layout> getLayout();

  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference list.
   * The list contents are of type {@link ui.languagedsl.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference list.
   * @see ui.languagedsl.LanguagedslPackage#getComponent_Element()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElement();

  /**
   * Returns the value of the '<em><b>Formuse</b></em>' containment reference list.
   * The list contents are of type {@link ui.languagedsl.FormUse}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formuse</em>' containment reference list.
   * @see ui.languagedsl.LanguagedslPackage#getComponent_Formuse()
   * @model containment="true"
   * @generated
   */
  EList<FormUse> getFormuse();

} // Component
