/*
 * generated by Xtext 2.30.0
 */
package com.mdsd.assignment3.ui.tests;

import com.google.inject.Injector;
import com.mdsd.assignment3.ui.internal.Assignment3Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathdslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Assignment3Activator.getInstance().getInjector("com.mdsd.assignment3.Mathdsl");
	}

}
