/**
 * generated by Xtext 2.30.0
 */
package interactive.fictiondsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see interactive.fictiondsl.FictiondslFactory
 * @model kind="package"
 * @generated
 */
public interface FictiondslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "fictiondsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Fictiondsl.interactive";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "fictiondsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FictiondslPackage eINSTANCE = interactive.fictiondsl.impl.FictiondslPackageImpl.init();

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.StoryImpl <em>Story</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.StoryImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getStory()
   * @generated
   */
  int STORY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__NAME = 0;

  /**
   * The feature id for the '<em><b>External</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__EXTERNAL = 1;

  /**
   * The feature id for the '<em><b>Scenario</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__SCENARIO = 2;

  /**
   * The number of structural features of the '<em>Story</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.ExternalImpl <em>External</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.ExternalImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getExternal()
   * @generated
   */
  int EXTERNAL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL__TYPE = 1;

  /**
   * The feature id for the '<em><b>Result</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL__RESULT = 2;

  /**
   * The number of structural features of the '<em>External</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.ScenarioImpl <em>Scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.ScenarioImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getScenario()
   * @generated
   */
  int SCENARIO = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__NAME = 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__VAR = 1;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__STATEMENT = 2;

  /**
   * The number of structural features of the '<em>Scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.VarDefImpl <em>Var Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.VarDefImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getVarDef()
   * @generated
   */
  int VAR_DEF = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DEF__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DEF__TYPE = 1;

  /**
   * The number of structural features of the '<em>Var Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DEF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.StatementImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Announce</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__ANNOUNCE = 0;

  /**
   * The feature id for the '<em><b>End</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__END = 1;

  /**
   * The feature id for the '<em><b>Question</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__QUESTION = 2;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.SomeRefImpl <em>Some Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.SomeRefImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getSomeRef()
   * @generated
   */
  int SOME_REF = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOME_REF__NAME = 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOME_REF__EXPRESSION = 1;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOME_REF__REF = 2;

  /**
   * The number of structural features of the '<em>Some Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOME_REF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.QuestionImpl <em>Question</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.QuestionImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getQuestion()
   * @generated
   */
  int QUESTION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__NAME = SOME_REF__NAME;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__EXPRESSION = SOME_REF__EXPRESSION;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__REF = SOME_REF__REF;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__TYPE = SOME_REF_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__EXREF = SOME_REF_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__OP = SOME_REF_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__CONDITION = SOME_REF_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Target</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__TARGET = SOME_REF_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Question</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_FEATURE_COUNT = SOME_REF_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.AnnounceImpl <em>Announce</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.AnnounceImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getAnnounce()
   * @generated
   */
  int ANNOUNCE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE__NAME = SOME_REF__NAME;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE__EXPRESSION = SOME_REF__EXPRESSION;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE__REF = SOME_REF__REF;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE__EXP = SOME_REF_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE__TARGET = SOME_REF_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Announce</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE_FEATURE_COUNT = SOME_REF_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.TargetImpl <em>Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.TargetImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getTarget()
   * @generated
   */
  int TARGET = 7;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__REF = 0;

  /**
   * The feature id for the '<em><b>Exref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__EXREF = 1;

  /**
   * The feature id for the '<em><b>Vardef</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__VARDEF = 2;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__CONDITION = 3;

  /**
   * The feature id for the '<em><b>Res</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__RES = 4;

  /**
   * The number of structural features of the '<em>Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.EndImpl <em>End</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.EndImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getEnd()
   * @generated
   */
  int END = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END__NAME = SOME_REF__NAME;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END__EXPRESSION = SOME_REF__EXPRESSION;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END__REF = SOME_REF__REF;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END__EXP = SOME_REF_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>End</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_FEATURE_COUNT = SOME_REF_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.ExpressionImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 9;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__TYPE = 1;

  /**
   * The feature id for the '<em><b>Add</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ADD = 2;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__REF = 3;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OP = 4;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__EXP = 5;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link interactive.fictiondsl.impl.EndingImpl <em>Ending</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see interactive.fictiondsl.impl.EndingImpl
   * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getEnding()
   * @generated
   */
  int ENDING = 11;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDING__NUMBER = EXPRESSION__NUMBER;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDING__TYPE = EXPRESSION__TYPE;

  /**
   * The feature id for the '<em><b>Add</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDING__ADD = EXPRESSION__ADD;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDING__REF = EXPRESSION__REF;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDING__OP = EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDING__EXP = EXPRESSION__EXP;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDING__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ending</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDING_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.Story <em>Story</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Story</em>'.
   * @see interactive.fictiondsl.Story
   * @generated
   */
  EClass getStory();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.Story#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see interactive.fictiondsl.Story#getName()
   * @see #getStory()
   * @generated
   */
  EAttribute getStory_Name();

  /**
   * Returns the meta object for the containment reference list '{@link interactive.fictiondsl.Story#getExternal <em>External</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>External</em>'.
   * @see interactive.fictiondsl.Story#getExternal()
   * @see #getStory()
   * @generated
   */
  EReference getStory_External();

  /**
   * Returns the meta object for the containment reference list '{@link interactive.fictiondsl.Story#getScenario <em>Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scenario</em>'.
   * @see interactive.fictiondsl.Story#getScenario()
   * @see #getStory()
   * @generated
   */
  EReference getStory_Scenario();

  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.External <em>External</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>External</em>'.
   * @see interactive.fictiondsl.External
   * @generated
   */
  EClass getExternal();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.External#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see interactive.fictiondsl.External#getName()
   * @see #getExternal()
   * @generated
   */
  EAttribute getExternal_Name();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.External#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see interactive.fictiondsl.External#getType()
   * @see #getExternal()
   * @generated
   */
  EAttribute getExternal_Type();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.External#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Result</em>'.
   * @see interactive.fictiondsl.External#getResult()
   * @see #getExternal()
   * @generated
   */
  EAttribute getExternal_Result();

  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.Scenario <em>Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scenario</em>'.
   * @see interactive.fictiondsl.Scenario
   * @generated
   */
  EClass getScenario();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.Scenario#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see interactive.fictiondsl.Scenario#getName()
   * @see #getScenario()
   * @generated
   */
  EAttribute getScenario_Name();

  /**
   * Returns the meta object for the containment reference list '{@link interactive.fictiondsl.Scenario#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Var</em>'.
   * @see interactive.fictiondsl.Scenario#getVar()
   * @see #getScenario()
   * @generated
   */
  EReference getScenario_Var();

  /**
   * Returns the meta object for the containment reference list '{@link interactive.fictiondsl.Scenario#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statement</em>'.
   * @see interactive.fictiondsl.Scenario#getStatement()
   * @see #getScenario()
   * @generated
   */
  EReference getScenario_Statement();

  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.VarDef <em>Var Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Def</em>'.
   * @see interactive.fictiondsl.VarDef
   * @generated
   */
  EClass getVarDef();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.VarDef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see interactive.fictiondsl.VarDef#getName()
   * @see #getVarDef()
   * @generated
   */
  EAttribute getVarDef_Name();

  /**
   * Returns the meta object for the containment reference '{@link interactive.fictiondsl.VarDef#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see interactive.fictiondsl.VarDef#getType()
   * @see #getVarDef()
   * @generated
   */
  EReference getVarDef_Type();

  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see interactive.fictiondsl.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the containment reference list '{@link interactive.fictiondsl.Statement#getAnnounce <em>Announce</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Announce</em>'.
   * @see interactive.fictiondsl.Statement#getAnnounce()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Announce();

  /**
   * Returns the meta object for the containment reference list '{@link interactive.fictiondsl.Statement#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>End</em>'.
   * @see interactive.fictiondsl.Statement#getEnd()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_End();

  /**
   * Returns the meta object for the containment reference list '{@link interactive.fictiondsl.Statement#getQuestion <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Question</em>'.
   * @see interactive.fictiondsl.Statement#getQuestion()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Question();

  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.Question <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Question</em>'.
   * @see interactive.fictiondsl.Question
   * @generated
   */
  EClass getQuestion();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.Question#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see interactive.fictiondsl.Question#getType()
   * @see #getQuestion()
   * @generated
   */
  EAttribute getQuestion_Type();

  /**
   * Returns the meta object for the reference '{@link interactive.fictiondsl.Question#getExref <em>Exref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Exref</em>'.
   * @see interactive.fictiondsl.Question#getExref()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_Exref();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.Question#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see interactive.fictiondsl.Question#getOp()
   * @see #getQuestion()
   * @generated
   */
  EAttribute getQuestion_Op();

  /**
   * Returns the meta object for the containment reference '{@link interactive.fictiondsl.Question#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see interactive.fictiondsl.Question#getCondition()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link interactive.fictiondsl.Question#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Target</em>'.
   * @see interactive.fictiondsl.Question#getTarget()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_Target();

  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.Announce <em>Announce</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Announce</em>'.
   * @see interactive.fictiondsl.Announce
   * @generated
   */
  EClass getAnnounce();

  /**
   * Returns the meta object for the containment reference '{@link interactive.fictiondsl.Announce#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see interactive.fictiondsl.Announce#getExp()
   * @see #getAnnounce()
   * @generated
   */
  EReference getAnnounce_Exp();

  /**
   * Returns the meta object for the containment reference '{@link interactive.fictiondsl.Announce#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Target</em>'.
   * @see interactive.fictiondsl.Announce#getTarget()
   * @see #getAnnounce()
   * @generated
   */
  EReference getAnnounce_Target();

  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.Target <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target</em>'.
   * @see interactive.fictiondsl.Target
   * @generated
   */
  EClass getTarget();

  /**
   * Returns the meta object for the reference '{@link interactive.fictiondsl.Target#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see interactive.fictiondsl.Target#getRef()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_Ref();

  /**
   * Returns the meta object for the reference '{@link interactive.fictiondsl.Target#getExref <em>Exref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Exref</em>'.
   * @see interactive.fictiondsl.Target#getExref()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_Exref();

  /**
   * Returns the meta object for the reference '{@link interactive.fictiondsl.Target#getVardef <em>Vardef</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Vardef</em>'.
   * @see interactive.fictiondsl.Target#getVardef()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_Vardef();

  /**
   * Returns the meta object for the containment reference '{@link interactive.fictiondsl.Target#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see interactive.fictiondsl.Target#getCondition()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_Condition();

  /**
   * Returns the meta object for the containment reference '{@link interactive.fictiondsl.Target#getRes <em>Res</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Res</em>'.
   * @see interactive.fictiondsl.Target#getRes()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_Res();

  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.End <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End</em>'.
   * @see interactive.fictiondsl.End
   * @generated
   */
  EClass getEnd();

  /**
   * Returns the meta object for the containment reference '{@link interactive.fictiondsl.End#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see interactive.fictiondsl.End#getExp()
   * @see #getEnd()
   * @generated
   */
  EReference getEnd_Exp();

  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see interactive.fictiondsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.Expression#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see interactive.fictiondsl.Expression#getNumber()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Number();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.Expression#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see interactive.fictiondsl.Expression#getType()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Type();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.Expression#getAdd <em>Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Add</em>'.
   * @see interactive.fictiondsl.Expression#getAdd()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Add();

  /**
   * Returns the meta object for the reference '{@link interactive.fictiondsl.Expression#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see interactive.fictiondsl.Expression#getRef()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Ref();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.Expression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see interactive.fictiondsl.Expression#getOp()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link interactive.fictiondsl.Expression#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see interactive.fictiondsl.Expression#getExp()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Exp();

  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.SomeRef <em>Some Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Some Ref</em>'.
   * @see interactive.fictiondsl.SomeRef
   * @generated
   */
  EClass getSomeRef();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.SomeRef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see interactive.fictiondsl.SomeRef#getName()
   * @see #getSomeRef()
   * @generated
   */
  EAttribute getSomeRef_Name();

  /**
   * Returns the meta object for the containment reference '{@link interactive.fictiondsl.SomeRef#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see interactive.fictiondsl.SomeRef#getExpression()
   * @see #getSomeRef()
   * @generated
   */
  EReference getSomeRef_Expression();

  /**
   * Returns the meta object for the reference '{@link interactive.fictiondsl.SomeRef#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see interactive.fictiondsl.SomeRef#getRef()
   * @see #getSomeRef()
   * @generated
   */
  EReference getSomeRef_Ref();

  /**
   * Returns the meta object for class '{@link interactive.fictiondsl.Ending <em>Ending</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ending</em>'.
   * @see interactive.fictiondsl.Ending
   * @generated
   */
  EClass getEnding();

  /**
   * Returns the meta object for the attribute '{@link interactive.fictiondsl.Ending#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see interactive.fictiondsl.Ending#getValue()
   * @see #getEnding()
   * @generated
   */
  EAttribute getEnding_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FictiondslFactory getFictiondslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.StoryImpl <em>Story</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.StoryImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getStory()
     * @generated
     */
    EClass STORY = eINSTANCE.getStory();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORY__NAME = eINSTANCE.getStory_Name();

    /**
     * The meta object literal for the '<em><b>External</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORY__EXTERNAL = eINSTANCE.getStory_External();

    /**
     * The meta object literal for the '<em><b>Scenario</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORY__SCENARIO = eINSTANCE.getStory_Scenario();

    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.ExternalImpl <em>External</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.ExternalImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getExternal()
     * @generated
     */
    EClass EXTERNAL = eINSTANCE.getExternal();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTERNAL__NAME = eINSTANCE.getExternal_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTERNAL__TYPE = eINSTANCE.getExternal_Type();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTERNAL__RESULT = eINSTANCE.getExternal_Result();

    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.ScenarioImpl <em>Scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.ScenarioImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getScenario()
     * @generated
     */
    EClass SCENARIO = eINSTANCE.getScenario();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCENARIO__NAME = eINSTANCE.getScenario_Name();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO__VAR = eINSTANCE.getScenario_Var();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO__STATEMENT = eINSTANCE.getScenario_Statement();

    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.VarDefImpl <em>Var Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.VarDefImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getVarDef()
     * @generated
     */
    EClass VAR_DEF = eINSTANCE.getVarDef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_DEF__NAME = eINSTANCE.getVarDef_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DEF__TYPE = eINSTANCE.getVarDef_Type();

    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.StatementImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Announce</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__ANNOUNCE = eINSTANCE.getStatement_Announce();

    /**
     * The meta object literal for the '<em><b>End</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__END = eINSTANCE.getStatement_End();

    /**
     * The meta object literal for the '<em><b>Question</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__QUESTION = eINSTANCE.getStatement_Question();

    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.QuestionImpl <em>Question</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.QuestionImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getQuestion()
     * @generated
     */
    EClass QUESTION = eINSTANCE.getQuestion();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUESTION__TYPE = eINSTANCE.getQuestion_Type();

    /**
     * The meta object literal for the '<em><b>Exref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__EXREF = eINSTANCE.getQuestion_Exref();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUESTION__OP = eINSTANCE.getQuestion_Op();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__CONDITION = eINSTANCE.getQuestion_Condition();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__TARGET = eINSTANCE.getQuestion_Target();

    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.AnnounceImpl <em>Announce</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.AnnounceImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getAnnounce()
     * @generated
     */
    EClass ANNOUNCE = eINSTANCE.getAnnounce();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANNOUNCE__EXP = eINSTANCE.getAnnounce_Exp();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANNOUNCE__TARGET = eINSTANCE.getAnnounce_Target();

    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.TargetImpl <em>Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.TargetImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getTarget()
     * @generated
     */
    EClass TARGET = eINSTANCE.getTarget();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__REF = eINSTANCE.getTarget_Ref();

    /**
     * The meta object literal for the '<em><b>Exref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__EXREF = eINSTANCE.getTarget_Exref();

    /**
     * The meta object literal for the '<em><b>Vardef</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__VARDEF = eINSTANCE.getTarget_Vardef();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__CONDITION = eINSTANCE.getTarget_Condition();

    /**
     * The meta object literal for the '<em><b>Res</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__RES = eINSTANCE.getTarget_Res();

    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.EndImpl <em>End</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.EndImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getEnd()
     * @generated
     */
    EClass END = eINSTANCE.getEnd();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference END__EXP = eINSTANCE.getEnd_Exp();

    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.ExpressionImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__NUMBER = eINSTANCE.getExpression_Number();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__TYPE = eINSTANCE.getExpression_Type();

    /**
     * The meta object literal for the '<em><b>Add</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__ADD = eINSTANCE.getExpression_Add();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__REF = eINSTANCE.getExpression_Ref();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__OP = eINSTANCE.getExpression_Op();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__EXP = eINSTANCE.getExpression_Exp();

    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.SomeRefImpl <em>Some Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.SomeRefImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getSomeRef()
     * @generated
     */
    EClass SOME_REF = eINSTANCE.getSomeRef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOME_REF__NAME = eINSTANCE.getSomeRef_Name();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOME_REF__EXPRESSION = eINSTANCE.getSomeRef_Expression();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOME_REF__REF = eINSTANCE.getSomeRef_Ref();

    /**
     * The meta object literal for the '{@link interactive.fictiondsl.impl.EndingImpl <em>Ending</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see interactive.fictiondsl.impl.EndingImpl
     * @see interactive.fictiondsl.impl.FictiondslPackageImpl#getEnding()
     * @generated
     */
    EClass ENDING = eINSTANCE.getEnding();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENDING__VALUE = eINSTANCE.getEnding_Value();

  }

} //FictiondslPackage
