/**
 * generated by Xtext 2.30.0
 */
package interactive.fictiondsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Some Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link interactive.fictiondsl.SomeRef#getName <em>Name</em>}</li>
 *   <li>{@link interactive.fictiondsl.SomeRef#getExpression <em>Expression</em>}</li>
 *   <li>{@link interactive.fictiondsl.SomeRef#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see interactive.fictiondsl.FictiondslPackage#getSomeRef()
 * @model
 * @generated
 */
public interface SomeRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see interactive.fictiondsl.FictiondslPackage#getSomeRef_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link interactive.fictiondsl.SomeRef#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see interactive.fictiondsl.FictiondslPackage#getSomeRef_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link interactive.fictiondsl.SomeRef#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(VarDef)
   * @see interactive.fictiondsl.FictiondslPackage#getSomeRef_Ref()
   * @model
   * @generated
   */
  VarDef getRef();

  /**
   * Sets the value of the '{@link interactive.fictiondsl.SomeRef#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(VarDef value);

} // SomeRef
