/**
 * generated by Xtext 2.30.0
 */
package interactive.fictiondsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Target</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link interactive.fictiondsl.Target#getRef <em>Ref</em>}</li>
 *   <li>{@link interactive.fictiondsl.Target#getExref <em>Exref</em>}</li>
 *   <li>{@link interactive.fictiondsl.Target#getVardef <em>Vardef</em>}</li>
 *   <li>{@link interactive.fictiondsl.Target#getCondition <em>Condition</em>}</li>
 *   <li>{@link interactive.fictiondsl.Target#getRes <em>Res</em>}</li>
 * </ul>
 *
 * @see interactive.fictiondsl.FictiondslPackage#getTarget()
 * @model
 * @generated
 */
public interface Target extends EObject
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(SomeRef)
   * @see interactive.fictiondsl.FictiondslPackage#getTarget_Ref()
   * @model
   * @generated
   */
  SomeRef getRef();

  /**
   * Sets the value of the '{@link interactive.fictiondsl.Target#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(SomeRef value);

  /**
   * Returns the value of the '<em><b>Exref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exref</em>' reference.
   * @see #setExref(External)
   * @see interactive.fictiondsl.FictiondslPackage#getTarget_Exref()
   * @model
   * @generated
   */
  External getExref();

  /**
   * Sets the value of the '{@link interactive.fictiondsl.Target#getExref <em>Exref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exref</em>' reference.
   * @see #getExref()
   * @generated
   */
  void setExref(External value);

  /**
   * Returns the value of the '<em><b>Vardef</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vardef</em>' reference.
   * @see #setVardef(VarDef)
   * @see interactive.fictiondsl.FictiondslPackage#getTarget_Vardef()
   * @model
   * @generated
   */
  VarDef getVardef();

  /**
   * Sets the value of the '{@link interactive.fictiondsl.Target#getVardef <em>Vardef</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vardef</em>' reference.
   * @see #getVardef()
   * @generated
   */
  void setVardef(VarDef value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Expression)
   * @see interactive.fictiondsl.FictiondslPackage#getTarget_Condition()
   * @model containment="true"
   * @generated
   */
  Expression getCondition();

  /**
   * Sets the value of the '{@link interactive.fictiondsl.Target#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Expression value);

  /**
   * Returns the value of the '<em><b>Res</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Res</em>' containment reference.
   * @see #setRes(Expression)
   * @see interactive.fictiondsl.FictiondslPackage#getTarget_Res()
   * @model containment="true"
   * @generated
   */
  Expression getRes();

  /**
   * Sets the value of the '{@link interactive.fictiondsl.Target#getRes <em>Res</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Res</em>' containment reference.
   * @see #getRes()
   * @generated
   */
  void setRes(Expression value);

} // Target
