/*
 * generated by Xtext 2.30.0
 */
package com.mdsd.assignment2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathdslScopeProvider extends DelegatingScopeProvider {
}
