/*
 * generated by Xtext 2.30.0
 */
package ui.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLanguagedslScopeProvider extends DelegatingScopeProvider {
}
