/**
 * generated by Xtext 2.30.0
 */
package com.mdsd.assignment2.mathdsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Math Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mdsd.assignment2.mathdsl.MathExp#getVariables <em>Variables</em>}</li>
 * </ul>
 *
 * @see com.mdsd.assignment2.mathdsl.MathdslPackage#getMathExp()
 * @model
 * @generated
 */
public interface MathExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link com.mdsd.assignment2.mathdsl.VarBinding}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see com.mdsd.assignment2.mathdsl.MathdslPackage#getMathExp_Variables()
   * @model containment="true"
   * @generated
   */
  EList<VarBinding> getVariables();

} // MathExp
