/**
 * generated by Xtext 2.30.0
 */
package com.mdsd.assignment2.mathdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mdsd.assignment2.mathdsl.VarBinding#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see com.mdsd.assignment2.mathdsl.MathdslPackage#getVarBinding()
 * @model
 * @generated
 */
public interface VarBinding extends Binding
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see com.mdsd.assignment2.mathdsl.MathdslPackage#getVarBinding_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link com.mdsd.assignment2.mathdsl.VarBinding#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

} // VarBinding
