/*
 * generated by Xtext 2.30.0
 */
package ui.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ui.parser.antlr.internal.InternalLanguagedslParser;
import ui.services.LanguagedslGrammarAccess;

public class LanguagedslParser extends AbstractAntlrParser {

	@Inject
	private LanguagedslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLanguagedslParser createParser(XtextTokenStream stream) {
		return new InternalLanguagedslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Title";
	}

	public LanguagedslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LanguagedslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
