/*
 * generated by Xtext 2.30.0
 */
package ui.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ui.LanguagedslRuntimeModule;
import ui.LanguagedslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LanguagedslIdeSetup extends LanguagedslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LanguagedslRuntimeModule(), new LanguagedslIdeModule()));
	}
	
}
